name: "Line Length Check"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ui.frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ui.frontend/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-line-length:
    name: Check Line Length
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for lines exceeding 120 characters
        run: |
          echo "# Line Length Check Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Find files with lines exceeding 120 characters in ui.frontend directory
          # Ensure grep outputs in "filename:line_number:content" format
          LONG_LINES=$(grep -r --include="*.*" -n ".\{121,\}" ui.frontend || true)
          
          if [ -z "$LONG_LINES" ]; then
            echo "✅ No lines exceeding 120 characters found in ui.frontend directory." >> $GITHUB_STEP_SUMMARY
            echo "::notice::No lines exceeding 120 characters found."
          else
            # Count total violations
            LINE_COUNT=$(echo "$LONG_LINES" | wc -l)
            echo "❌ Found $LINE_COUNT lines exceeding 120 characters in ui.frontend directory:" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # Create a table for the results
            echo "| File | Line | Content |" >> $GITHUB_STEP_SUMMARY
            echo "| ---- | ---- | ------- |" >> $GITHUB_STEP_SUMMARY
            
            # Create a file for compact display of all violations
            echo "# All Line Length Violations" > line_violations.txt
            echo "" >> line_violations.txt
            
            # Process each line and add to the summary
            echo "$LONG_LINES" | while read -r line_info; do
              # Parse the line info (handling potential colons in the content)
              file=$(echo "$line_info" | cut -d':' -f1)
              line_num=$(echo "$line_info" | cut -d':' -f2)
              content=$(echo "$line_info" | cut -d':' -f3-)
              
              # Truncate content if too long for display
              if [ ${#content} -gt 100 ]; then
                display_content="${content:0:97}..."
              else
                display_content="$content"
              fi
              
              # Escape content for markdown table
              display_content=$(echo "$display_content" | sed 's/|/\\|/g')
              
              echo "| $file | $line_num | $display_content |" >> $GITHUB_STEP_SUMMARY
              
              # Add to the violations file
              echo "File: $file, Line: $line_num" >> line_violations.txt
              
              # Create annotations visible in GitHub UI with clear file path
              echo "::warning file=$file,line=$line_num::Line in $file:$line_num exceeds 120 characters"
            done
            
            # Print all violations to console for clarity
            cat line_violations.txt
            
            # Generate file-based summary for clearer output
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## Files with violations" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # Count violations per file and display in sorted order
            echo "$LONG_LINES" | cut -d':' -f1 | sort | uniq -c | sort -nr | 
            while read -r count file; do
              echo "- **$file**: $count violation(s)" >> $GITHUB_STEP_SUMMARY
            done
            
            # Make the check fail if we found any violations
            echo "::error::Found $LINE_COUNT lines exceeding 120 characters in ui.frontend directory. See job summary and console output for details."
            exit 1
          fi